services:
  prometheus:
    env_file:
      - ../.env
    image: prom/prometheus:latest
    container_name: ${PROJECT_NAME}-prometheus
    volumes:
      - ./${PROMETHEUS_CONFIG_FILE}:/etc/prometheus/prometheus-config.yml
    command:
      - "--config.file=/etc/prometheus/prometheus-config.yml"
      - "--web.route-prefix=/prometheus"
      - "--web.external-url=http://localhost:9090/prometheus"
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring-network

  loki:
    env_file:
      - ../.env
    image: grafana/loki:latest
    container_name: ${PROJECT_NAME}-loki
    ports:
      - "${LOKI_PORT}:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - monitoring-network

  grafana:
    env_file:
      - ../.env
    image: grafana/grafana:latest
    container_name: ${PROJECT_NAME}-grafana
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - ./${DATASOURCES_CONFIG_FILE}:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - ./dashboards:/var/lib/grafana/dashboards
    ports:
      - "${GRAFANA_PORT}:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge

volumes:
  loki_data: