global:
    scrape_interval: 15s

scrape_configs:
    - job_name: prometheus
      metrics_path: "/actuator/prometheus"
      static_configs:
          - targets:
                [
                    "host.docker.internal:${PROMETHEUS_PORT_1}",
                    "host.docker.internal:${PROMETHEUS_PORT_2}",
                ]
