services:
    mariadb:
        image: mariadb:latest
        container_name: ${PROJECT_NAME}-mariadb
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATRABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - mysql_data:/vat/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - backend

    redis:
        image: redis:latest
        container_name: ${PROJECT_NAME}-redis
        ports:
            - "${REDIS_PORT}:6379"
        networks:
            - backend

networks:
    backend:
        driver: bridge

volumes:
    mysql_data:
