CREATE DATABASE IF NOT EXISTS FONTORY;
CREATE DATABASE IF NOT EXISTS TESTDB;

CREATE USER IF NOT EXISTS 'maria_fontory'@'%' IDENTIFIED BY 'maria_fontoryPW';

GRANT ALL PRIVILEGES ON FONTORY.* TO 'maria_fontory'@'%';
GRANT ALL PRIVILEGES ON TESTDB.* TO 'maria_fontory'@'%';

FLUSH PRIVILEGES;