apiVersion: 1

deleteDatasources:
    - name: prometheus
    - name: loki

datasources:
    - name: prometheus
      uid: prometheus
      type: prometheus
      access: proxy
      url: http://${PROJECT_NAME}-prometheus:9090/prometheus
      isDefault: true
      editable: true

    - name: loki
      uid: loki
      type: loki
      access: proxy
      url: http://${PROJECT_NAME}-loki:${LOKI_PORT}
      isDefault: false
      editable: true
